<?php

namespace Invoice\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsServicesRepository extends EntityRepository
{
}
